local vim = vim
local bind = vim.keymap.set
local telescope = require('telescope.builtin')
local dap = require('dap')
local widgets = require('dap.ui.widgets')

bind('n', '<leader>fn', function() vim.lsp.buf.document_symbol() end)
bind('n', '<leader>fm', function() vim.lsp.buf.format() end)
bind('n', '<leader>rn', function() vim.lsp.buf.rename() end)
bind('n', 'K', function() vim.lsp.buf.hover() end)
bind('n', '<C-k>', function() vim.lsp.buf.signature_help() end)
bind('n', '<leader>sa', function() vim.lsp.buf.code_action() end)
bind('n', 'gd', function() vim.lsp.buf.definition() end)
bind('n', '<leader>sd', function() vim.diagnostic.open_float({ focusable = true }) end)
bind('n', '<leader>sk', function() vim.lsp.diagnostic.goto_prev() end)
bind('n', '<leader>sj', function() vim.lsp.diagnostic.goto_next() end)
bind('n', '<leader>ss', function() telescope.diagnostics() end)

bind('n', '<leader>dc', function() dap.continue() end)
bind('n', '<leader>db', function() dap.toggle_breakpoint() end)
bind('n', '<leader>K', function() widgets.hover() end)
bind('n', '<leader>sc', function() widgets.cursor_float(widgets.scopes) end)
bind('n', '<leader>dn', function() dap.step_over() end)
bind('n', '<leader>ds', function() dap.step_into() end)
bind('n', '<leader>dr', function()
  dap.repl.toggle({ width = 20 }, 'vertical split')
  vim.cmd("wincmd h")
  vim.cmd("wincmd L")
  vim.cmd("wincmd h")
  -- vim.cmd("65 wincmd <")
end)
bind('n', '<leader>dt', function() dap.terminate() end)
bind('n', '<leader>dl', function() dap.run_last() end)
bind('n', '<leader>dl', function() dap.run_last() end)
bind('n', '<leader>cb', function() dap.clear_breakpoints() end)
