#!/bin/bash
# This script is used to increase/decrease the brightness

script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi 
done

if [ "$1" = "up" ]; then
  brightnessctl set +10%
elif [ "$1" = "down" ]; then
  brightnessctl set 10%-
fi
