#!/bin/bash
# This script is used to increase/decrease/mute the volume of the system
# It also show and hide the eww volume-popup.

script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi 
done

if [ "$1" = "up" ]; then
    amixer -D pulse sset Master 5%+
elif [ "$1" = "down" ]; then
    amixer -D pulse sset Master 5%-
elif [ "$1" = "mute" ]; then
    amixer -D pulse set Master 1+ toggle
fi
