#!/bin/bash
# This script is used to increase/decrease/mute the volume of the system
# It also show and hide the eww volume-popup.

script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi 
done

if [ "$1" = "up" ]; then
    wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
elif [ "$1" = "down" ]; then
    wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%-
elif [ "$1" = "mute" ]; then
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
fi
