right_format = """
  $time
"""

[battery]
disabled = true

[directory]
style = 'bold #ffffff'
format = ' [$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '~/.../'

[gcloud]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style = 'bold italic'
time_format = '%R'

[os]
disabled = false
style = 'bold #1793d1'
format = ' [$symbol]($style) [󰇙](#ffffff) '
  [os.symbols]
  Arch = ""

[character]
success_symbol = "[](#8ff48a)"
vimcmd_symbol = "[](#019833)"

[cmd_duration]
disabled = true

# Git
[git_branch]
symbol = " "
style = "#f1502f"

[git_status]
modified = '$count[!](#f7903b) '
deleted = '$count[](red) '
untracked = '$count[?](yellow) '
staged = '$count[+](green) '
style = 'bold #ffffff'
format = '([$all_status $ahead_behind]($style))'

# Programming Languages
[c]
format = "[$symbol]($style) "
symbol = ' '
style = "#ffffff"

[python]
format = "[$symbol]($style) "
symbol = ' Python 󰌠'
style = '#ffde57'

[scala]
format = "[$symbol]($style) "
symbol = ' Scala '
style = '#de3423'

[rust]
format = "[$symbol]($style) "
symbol = ' Rust '
style = '#B7410E'

[java]
format = "[$symbol]($style) "
symbol = ' Java '
style = '#f14c4d'

[lua]
format = "[$symbol]($style) "
symbol = ' Lua '
style = '#ffffff'

[golang]
format = "[$symbol]($style) "
symbol = ' Golang '
style = '#29beb0'

[dotnet]
format = "[$symbol]($style) "
symbol = ' .NET'
style = '#6c7cdc'

[nodejs]
format = "[$symbol]($style) "
symbol = ' Node.js '
style = '#6cc24a'

[package]
format = '\[[$symbol $version]($style)\] '
symbol = '󰏖'
style = 'bold #eeb38c'
