right_format = """
  $time
"""

[battery]
disabled = true

[directory]
style = 'bold #ffffff'
format = ' [$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '~/[...]/'

[gcloud]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style = 'bold italic #ffffff'
time_format = '%R'

[os]
disabled = false
style = 'bold #1793d1'
format = ' [$symbol]($style) [󰇙](#ffffff) '
  [os.symbols]
  Arch = ""

[character]
success_symbol = "[](#8ff48a)"
vimcmd_symbol = "[](#019833)"

[cmd_duration]
min_time = 5000
format = ' - 󱎫 [$duration]($style)'

# Git
[git_branch]
symbol = " "
style = "bold #f1502f"

[git_status]
modified = ' [!](bold yellow)[$count](bold #ffffff) '
deleted = ' (red)[$count](bold #ffffff) '
untracked = ' [?](bold blue)[$count](bold #ffffff) '

# Programming Languages
[c]
format = "[$symbol]($style) "
symbol = ''
style = "#283593 bold"

[python]
format = "[$symbol]($style) "
symbol = ' '
style = '#ffde57 bold'

[scala]
format = "[$symbol]($style) "
symbol = ''
style = '#de3423 bold'

[rust]
format = "[$symbol]($style) "
symbol = ''
style = '#ce412b bold'

[java]
format = "[$symbol]($style) "
symbol = ''
style = '#FFA518 bold'

[lua]
format = "[$symbol]($style) "
symbol = ''
style = '#000081 bold'

[package]
format = '\[[$symbol $version]($style)\] '
symbol = '󰏖'
style = 'bold #eeb38c'
