preload=/home/heikmike/Documents/Repositories/Wallpapers/spider-man-spiderverse.jpg
preload=/home/heikmike/Documents/Repositories/Wallpapers/spider-man-spiderverse-logo.png
preload=/home/heikmike/Documents/Repositories/Wallpapers/obi-wan.jpg
preload=/home/heikmike/Documents/Repositories/Wallpapers/obi-wan-darth.jpg
preload=/home/heikmike/Documents/Repositories/Wallpapers/barcelona.jpg
preload=/home/heikmike/Documents/Repositories/Wallpapers/messi.jpg

wallpaper=,/home/heikmike/Documents/Repositories/Wallpapers/spider-man-spiderverse.jpg
