preload = /home/heikmike/Documents/Repositories/Wallpapers/casey-horner-KR03PvYv3Fs-unsplash.jpg 
wallpaper = eDP-1,/home/heikmike/Documents/Repositories/Wallpapers/casey-horner-KR03PvYv3Fs-unsplash.jpg 
