$folder=~/.config/hypr/launchers

# Applications Launcher
bind = SUPER, R, exec, rofi -modi drun -show drun -theme $folder/configurations/rofi_launcher.rasi

# Configs Launcher 
bind = SUPER, comma, exec, rofi -modi Configs:$folder/scripts/rofi_configs.sh -show Configs -theme $folder/configurations/rofi_configs.rasi

