vim.g.mapleader = " "
vim.keymap.set("n", "<leader>h", vim.cmd.Ex)
vim.keymap.set("n", "<leader>y", 'Vyp') 
vim.keymap.set("n", ",", "/")
vim.keymap.set("n", "cg", "f\"ci\"")
vim.keymap.set("n", "cp", "ci(")
vim.keymap.set("n", "cs", "f[ci[")
vim.keymap.set("n", "fg", "f\"")
vim.keymap.set("n", "Fg", "F\"")
vim.keymap.set("n", "fp", "f(")
vim.keymap.set("n", "Fp", "F(")
vim.keymap.set("i", "<", "\\")
vim.keymap.set("i", "\\", "<")
vim.keymap.set("v", "<leader>y", '"+y')
vim.keymap.set("n", "U", '<C-R>')
