local keymap = vim.keymap.set

vim.g.mapleader = " "
keymap("n", "<leader>h", vim.cmd.Ex)
keymap("n", "<leader>y", 'Vyp')
keymap("n", ",", "/")
keymap("n", "cb", "ci{")
keymap("n", "fb", "f{")
keymap("n", "Fb", "F{")
keymap("n", "cs", "f[ci[")
keymap("n", "fs", "f[")
keymap("n", "Fs", "F[")
keymap("n", "cg", "f\"ci\"")
keymap("n", "fg", "f\"")
keymap("n", "Fg", "F\"")
keymap("n", "cp", "ci(")
keymap("n", "fp", "f(")
keymap("n", "Fp", "F(")
keymap("i", "<", "\\")
keymap("i", "\\", "<")
keymap("v", "<leader>y", '"+y')
keymap("n", "U", '<C-R>')
keymap("n", "<leader><leader>", ":bu#<CR>")
